#!/usr/bin/env sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/../.." || return; pwd)"

chartName="ffc-demo-web"

(
  cd "${projectRoot}"

  helm delete --purge \
    ${chartName}-redis \
    ${chartName}
)
