#!/usr/bin/env sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/../.." || return; pwd)"

chartName="ffc-demo-web"
namespace="ffc-demo"

show_help() {
  echo "
Install service to current Kubernetes context.

Usage: scripts/helm/install [OPTION...]

Options:
  -a, --auth  enable basic auth with username 'defra' (will prompt for password)
  -h, --help  display this help text
"
}

while :; do
  case $1 in
    -a|--auth)
      auth="true"
      ;;

    -h|--help)
      show_help
      exit 0
      ;;

    --)
      shift
      break
      ;;

    -?*)
      echo "Unrecognised argument: $1"
      show_help
      exit 1
      ;;

    *)
      break
  esac

  shift
done

if [ "${auth}" = "true" ]; then
  read -p "Username: " username
  credentials=$(htpasswd -n "${username}" | base64)
fi

(
  cd "${projectRoot}"

  echo "Deploying web redis"
  helm upgrade \
    --atomic \
    --install \
    --namespace ${namespace} \
    --values helm/${chartName}/redis-values.yaml \
    --wait \
    ${chartName}-redis \
    stable/redis

  echo "Deploying web service"
  helm upgrade \
    --atomic \
    --install \
    --namespace ${namespace} \
    --values helm/${chartName}/development-values.yaml \
    --set auth="${credentials}" \
    --wait \
    ${chartName} \
    ./helm
)
