#!/bin/sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

(
  cd "${projectRoot}"
  helm upgrade ffc-demo-web --install --namespace ffc-demo --values ./helm/dev-values.yaml ./helm --set auth=$MINE_BASIC_AUTH
)
