#!/bin/sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

(
  cd "${projectRoot}"
  helm upgrade mine-support --install --namespace mine-support --values ./helm/dev-values.yaml ./helm --set auth=$MINE_BASIC_AUTH
)
